"""Generates docs/source_register.md from the 9 real contract objects in
reconcilegate/contracts.py (themselves loaded from contracts/*.yaml).
Re-runnable; every row traces to a real contract field, nothing here is
hand-invented (tests/test_register.py checks exactly that property).
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from reconcilegate.contracts import CONTRACTS

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build_register_lines(contracts: dict) -> list:
    lines = [
        "# Generated source register",
        "",
        "Generated by `scripts/generate_source_register.py` from `contracts/*.yaml` "
        "via `reconcilegate/contracts.py`. Do not hand-edit; rerun the script instead.",
        "",
    ]
    for name in sorted(contracts):
        c = contracts[name]
        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"- kind: {c.kind}")
        lines.append(f"- owner: {c.owner}")
        lines.append(f"- natural key: {', '.join(c.natural_key)}")
        lines.append(f"- watermark column: {c.watermark_column}")
        lines.append(f"- refresh window: {c.refresh_window_hours} hours")
        lines.append(f"- late-arrival window: {c.late_arrival_window_hours} hours")
        lines.append("")
        lines.append("| column | dtype | nullable | min | max |")
        lines.append("|---|---|---|---|---|")
        for f in c.fields:
            lines.append(
                f"| {f.name} | {f.dtype} | {f.nullable} "
                f"| {'' if f.min_value is None else f.min_value} "
                f"| {'' if f.max_value is None else f.max_value} |"
            )
        lines.append("")
    return lines


def main():
    lines = build_register_lines(CONTRACTS)
    out_path = os.path.join(ROOT, "docs", "source_register.md")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out_path} ({len(CONTRACTS)} sources)")


if __name__ == "__main__":
    main()
